Sociala/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace= 'home')),
    path('account/', include('account.urls', namespace= 'account'))
]

account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name = 'register'),
    path('login/', views.LoginView.as_view(), name = 'login'),
    path('logout/', views.LogoutView.as_view(), name = 'logout'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name = 'profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name = 'reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name = 'password_reset_done'),
    path('confrim/<uidb64>/<token>/', views.PasswordResetConfrimView.as_view(), name = 'password_reset_confirm'),
    path('confrim/compelete', views.PasswordResetCompeleteView.as_view(), name = 'password_reset_complete'),
    path('follow/<int:user_id>/', views.FollowView.as_view(), name = 'follow'),
    path('unfollow/<int:user_id>/', views.UnfollowView.as_view(), name = 'unfollow'),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name= "home"),
    path('post/<int:post_id>/<slug:post_slug>/', views.PostView.as_view(), name = 'post'),
    path('post/delete/<int:post_id>/', views.DeleteView.as_view(), name = 'delete'),
    path('post/update/<int:post_id>/', views.UpdateView.as_view(), name = 'update'),
    path('post/create', views.CreateView.as_view(), name = 'create'),

]

templates/inc/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <div class="navbar-nav">
            <a class="nav-link active" href= "{% url "home:home" %}">Home</a>
            {% if request.user.is_authenticated %}
            <a class = 'nav-link active' href = "{% url "account:logout" %}"> Logout </a>
            <a class = 'nav-link active' href = {% url "account:profile" request.user.id %}> Profile </a>
            {% else %}
            <a class = 'nav-link active' href = "{% url "account:register" %}"> Register </a>
            <a class = 'nav-link active' href = "{% url "account:login" %}"> Login </a>
            {% endif %}
      </div>
    </div>
  </nav>

templates/inc/messages.html
{% if messages %}
{% for message in messages %}
<div class = 'col-md-6'>
<p class = 'alert alert-{{ message.tags }}'> {{ message }} </p>
</div>
{% endfor %}
{% else %}
{% endif %}